[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
verbosity = 3
solc-version = '0.8.21'
via_ir = true
optimizer = true
optimizer_runs = 1000000000

remappings = [
    'forge-std/=lib/forge-std/src/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'solmate/=lib/solmate/src/'
]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
base = "${BASE_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
# See more config options https://github.com/foundry-rs/foundry/tree/master/config